name: leolivier
favicon: null
layout_spectrum: 0
typography_spectrum: 0.85675
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1875
  lightness: 0.12380036665126681
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
