name: leolivier
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85675
title: leolivierphotography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b2a8a6'
    - '#efeff1'
    - '#7a7571'
    - '#3b3b3b'
  brandStrength: 1
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
